name: Post dependency compare link

on:
  workflow_call:
    inputs:
      dep:
        type: string
        required: true
jobs:
  post-comment:
    name: Post comment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Generate a GitHub link to a page that displays all commits/changes between
      # the old dependency version and the new one, or an empty string if the dependency
      # wasn't changed.
      - name: Get compare URL
        id: get-compare-url
        run: |
          compare_url=$(git diff -r ${{ github.base_ref }} \
            | grep ${{ inputs.dep }}\/archive \
            | cut -d '/' -f 7 \
            | cut -d '.' -f 1 \
            | awk 'NR%2{printf "https://github.com/codecov/${{ inputs.dep }}/compare/%s..",$0;next;}1')
          echo "COMPARE_URL=$(compare_url)" >> $GITHUB_OUTPUT

      # If our dep was changed, check if we've already made a comment and cached its ID
      - name: Cache check
        id: cache-check
        if: steps.get-compare-url.outputs.COMPARE_URL != ''
        uses: actions/cache@v4
        with:
          path: comment-id.txt
          key: comment-id-${{ github.sha }}

      # If our dep was changed and there is no comment ID in the cache, create a new comment
      - name: Create comment
        id: create-comment
        if: ${{ steps.get-compare-url.outputs.COMPARE_URL != '' && steps.cache-check.outputs.cache-hit != 'true' }}
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'This PR includes changes to `${{ inputs.dep }}`. Please review them here: ${{ steps.get-compare-url.outputs.COMPARE_URL }}'
            })

      - name: Get comment ID
        id: get-comment-id
        run: |
          if [ ! -f comment-id.txt ]; then
            echo "${{ steps.create-comment.outputs.result }}" | jq '.id' > comment-id.txt
          fi
          echo "COMMENT_ID=$(cat comment-id.txt)" >> $GITHUB_OUTPUT

      - name: Update comment
        id: update-comment
        if: ${{ steps.get-compare-url.outputs.COMPARE_URL != '' && steps.cache-check.outputs.cache-hit == 'true' }}
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.updateComment({
              comment_id: ${{ steps.get-comment-id.outputs.COMMENT_ID }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'This PR includes changes to `${{ inputs.dep }}`. Please review them here: ${{ steps.get-compare-url.outputs.COMPARE_URL }}'
            })
