
name: Run Lint

on:
  workflow_call:
    inputs:
      working_directory:
        type: string
        default: .

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: make lint.install
      - name: Check
        run: make lint.check
