
name: Run Lint

on:
  workflow_call:

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: make lint.install
      - name: Check
        run: make lint.check