name: Patch typing check

on:
  workflow_call:
    inputs:
      extra_config:
        type: string
        required: false
        default: ""
        description: "Extra configuration for mypy"
      working_directory:
        type: string
        default: .

jobs:
  static-type-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install mypy==1.13.0
      - run: mypy . --ignore-missing-imports ${{ inputs.extra_config }}
