
name: Run ATS

on:
  workflow_call:
    inputs:
      repo:
        type: string
        required: true
      container:
        type: string
        required: true
      codecov_cli_upload_args:
        required: false
        type: string
        default: ''
        description: 'List of args to pass to cli on upload. This is kind of a hack pending a more robust solution'
env:
  AR_REPO: ${{ inputs.repo }}

jobs:
  ats:
    name: ATS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cache App
        id: cache-app
        uses: actions/cache@v3
        env:
          cache-name: cache-app
        with:
          path: |
            app.tar
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.run_id }}
      - name: Load built image
        run: |
          docker load --input app.tar
          make tag.latest

      - name: Install docker compose
        run: |
          sudo curl -SL https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - name: Bring test env up
        run: |
          make test_env.up
      - name: Prepare for tests
        run: |
          make test_env.prepare
          make test_env.check_db
      - id: test-upload
        uses: codecov/codecov-ats-docker@main
        name: Run tests and upload to Codecov
        with:
          container: ${{ inputs.container }}
          codecov_cli_upload_args: ${{ inputs.codecov_cli_upload_args }}
          static_token: ${{ secrets.STATIC_TOKEN }}
          codecov_token: ${{ secrets.CODECOV_ORG_TOKEN }}