
name: Run Tests

on:
  workflow_call:
    inputs:
      run_integration:
        required: false
        type: boolean
        default: true
      repo:
        type: string
        required: true
env:
  AR_REPO: ${{ inputs.repo }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cache App
        id: cache-app
        uses: actions/cache@v3
        env:
          cache-name: cache-app
        with:
          path: |
            app.tar
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.run_id }}
      - name: Load built image
        run: |
          docker load --input app.tar
      - name: Install docker compose
        run: |
          sudo curl -SL https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - name: Bring test env up
        run: |
          make test_env.up
      - name: Prepare for tests
        run: |
          make test_env.prepare
          make test_env.check_db
      - name: Run unit tests
        run: |
          make test_env.run_unit
      - name: Run integration tests
        if: inputs.run_integration == true
        run: |
          make test_env.run_integration

      - name: Upload using codecov action
        if: ${{ !github.event.pull_request.head.repo.fork && github.repository_owner == 'codecov' }}
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrests.CODECOV_ORG_TOKEN }}
          url: ${{ secrests.CODECOV_URL }}

      - name: Upload using codecov action (staging)
        if: ${{ !github.event.pull_request.head.repo.fork && github.repository_owner == 'codecov' }}
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrests.CODECOV_ORG_TOKEN_STAGING }}
          url: ${{ secrests.CODECOV_STAGING_URL }}

      - name: Upload using codecov action (QA)
        if: ${{ !github.event.pull_request.head.repo.fork && github.repository_owner == 'codecov' }}
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrests.CODECOV_QA_TOKEN }}
          url: ${{ secrests.CODECOV_QA_URL }}

      - name: Upload using codecov action (Public QA)
        if: ${{ !github.event.pull_request.head.repo.fork && github.repository_owner == 'codecov' }}
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrests.CODECOV_PUBLIC_QA_TOKEN }}
          url: ${{ secrests.CODECOV_PUBLIC_QA_URL }}
      
      - name: Upload using test results action
        if: ${{ !cancelled() && !github.event.pull_request.head.repo.fork && github.repository_owner == 'codecov' }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrests.CODECOV_ORG_TOKEN }}
          url: ${{ secrests.CODECOV_URL }}

      - name: Upload using test results action (staging)
        if: ${{ !cancelled() && !github.event.pull_request.head.repo.fork && github.repository_owner == 'codecov' }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrests.CODECOV_ORG_TOKEN_STAGING }}
          url: ${{ secrests.CODECOV_STAGING_URL }}

      - name: Upload using test results action (QA)
        if: ${{ !cancelled() && !github.event.pull_request.head.repo.fork && github.repository_owner == 'codecov' }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrests.CODECOV_QA_TOKEN }}
          url: ${{ secrests.CODECOV_QA_URL }}

      - name: Upload using test results action (Public QA)
        if: ${{ !cancelled() && !github.event.pull_request.head.repo.fork && github.repository_owner == 'codecov' }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrests.CODECOV_PUBLIC_QA_TOKEN }}
          url: ${{ secrests.CODECOV_PUBLIC_QA_URL }}