name: Self Hosted Build and Release
on:
  workflow_call:
    inputs:
      push_rolling:
        type: boolean
        default: false
        description: "Whether to push the rolling image"
      push_release:
        type: boolean
        default: false
        description: "Whether to push the release image"
      repo:
        type: string
        required: true
      cache_requirements:
        type: boolean
        default: true
env:
  AR_REPO: ${{ inputs.repo }}

jobs:
  build-self-hosted:
    name: Build Self Hosted App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: "auth"
        if: ${{ !github.event.pull_request.head.repo.fork && github.repository_owner == 'codecov' && inputs.cache_requirements }}
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2.1.2"
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ secrets.CODECOV_GCP_WIDP }}
          service_account: ${{ secrets.CODECOV_GCP_WIDSA }}

      - name: Docker configuration
        if: ${{ !github.event.pull_request.head.repo.fork && github.repository_owner == 'codecov' && inputs.cache_requirements }}
        run: |-
          echo ${{steps.auth.outputs.access_token}} | docker login -u oauth2accesstoken --password-stdin https://us-docker.pkg.dev

      - name: Cache Requirements
        id: cache-requirements
        if: inputs.cache_requirements
        uses: actions/cache@v4
        env:
          cache-name: cache-requirements
        with:
          path: |
            requirements.tar
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/docker/Dockerfile.requirements') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: Cache Self hosted
        id: cache-self-hosted
        uses: actions/cache@v4
        env:
          cache-name: cache-self-hosted
        with:
          path: |
            self-hosted-runtime.tar
            self-hosted.tar
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.run_id }}

      - name: Load requirements from cache
        if: ${{ steps.cache-requirements.outputs.cache-hit == 'true' && inputs.cache_requirements }}
        run: |
          make load.requirements

      - name: Build/pull requirements
        if: ${{ steps.cache-requirements.outputs.cache-hit != 'true' && inputs.cache_requirements }}
        run: |
          make build.requirements

      - name: Load built image
        if: ${{ steps.cache-self-hosted.outputs.cache-hit == 'true' }}
        run: |
          make load.self-hosted

      - name: Build self hosted
        if: ${{ steps.cache-self-hosted.outputs.cache-hit != 'true' }}
        run: |
          make build.self-hosted
          make save.self-hosted

  self-hosted:
    name: Push Self Hosted Image
    needs: [build-self-hosted]
    if: inputs.push_rolling == true && github.repository_owner == 'codecov' && !github.event.pull_request.head.repo.fork
    runs-on: ubuntu-latest
    environment: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cache Self hosted
        id: cache-self-hosted
        uses: actions/cache@v4
        env:
          cache-name: cache-self-hosted
        with:
          path: |
            self-hosted-runtime.tar
            self-hosted.tar
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.run_id }}
      - name: Load built image
        run: |
          make load.self-hosted
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.CODECOV_DEVOPS_DOCKER_USERNAME }}
          password: ${{ secrets.CODECOV_DEVOPS_DOCKER_PASSWORD }}
      - name: Push Self Hosted Rolling
        run: |
          make tag.self-hosted-rolling
          make push.self-hosted-rolling
  self-hosted-release:
    name: Push Self Hosted Release Image
    needs: [build-self-hosted]
    if: inputs.push_release == true && github.repository_owner == 'codecov' && !github.event.pull_request.head.repo.fork
    runs-on: ubuntu-latest
    environment: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cache Self hosted
        id: cache-self-hosted
        uses: actions/cache@v4
        env:
          cache-name: cache-self-hosted
        with:
          path: |
            self-hosted-runtime.tar
            self-hosted.tar
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.run_id }}
      - name: Load built image
        run: |
          make load.self-hosted
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.CODECOV_DEVOPS_DOCKER_USERNAME }}
          password: ${{ secrets.CODECOV_DEVOPS_DOCKER_PASSWORD }}
      - name: Push self hosted release
        run: |
          make tag.self-hosted-release
          make push.self-hosted-release
